name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos:
    name: Tests
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.3
      - uses: actions/checkout@v4
      - name: Tests
        run: xcodebuild build test -project TMLPersistentContainer.xcodeproj -scheme TMLPersistentContainer-macOS -enableCodeCoverage YES
      - name: Generate coverage
        uses: sersoft-gmbh/swift-coverage-action@v4
        id: coverage-files
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: ${{ join(fromJSON(steps.coverage-files.outputs.files), ',') }}
