name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos:
    name: Tests
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: xcodebuild build test -project TMLPersistentContainer.xcodeproj -scheme TMLPersistentContainer-macOS -enableCodeCoverage YES
      - name: Generate coverage
        uses: sersoft-gmbh/swift-coverage-action@v2
        with:
          format: lcov
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: .swiftcov/TMLPersistentContainer.framework.coverage.lcov
